import React, { useState, useEffect } from 'react';
import { useEntityList } from '../DataHook/useEntityList';
import { client } from '../DataHook/amplifyClient';

// 🟢 BULLETPROOF PHONE EXTRACTOR
const safeExtractPhone = (customerId) => {
    if (!customerId || String(customerId).includes('undefined')) return "Unknown";
    
    let rawPhone = String(customerId);
    if (rawPhone.includes('#')) {
        rawPhone = rawPhone.split('#').pop(); // Grabs the very last part of CUSTOMER#biz#phone
    }

    const clean = rawPhone.replace(/\D/g, ''); // Strip all non-numbers
    if (clean.length > 8) {
        return clean.replace(/(\d{3,4})(\d{4})(\d+)/, '+$1 $2 $3');
    }
    return clean.length > 5 ? '+' + clean : "Unknown";
};

const OrderDetailModal = ({ orderId, orderStatus, orderTotal, customerId, customerName, phoneNbr, agentId, agentName, onClose }) => {
    
    // 1. Safe Keys
    const formattedPhone = String(phoneNbr).startsWith('+') ? String(phoneNbr) : `+${phoneNbr}`;
    const exactOrderId = String(orderId).replace('ORDER#', '');
    const targetPk = `ORDER#${formattedPhone}#${exactOrderId}`;
    const businessPk = `BUSINESS#${formattedPhone}`;

    // 2. Query Items (Fallback for older orders)
    const { data: lineItems, loading } = useEntityList(
        { pk: targetPk, sk: { beginsWith: 'ITEM#' }, sortDirection: 'DESC' },
        "listByBusiness" 
    );

    // 3. States for Advanced Order Tracking
    const [agentProfileName, setAgentProfileName] = useState(agentName || "");
    const [orderSummary, setOrderSummary] = useState(null);
    const [richItems, setRichItems] = useState(null);
    const [loadingSummary, setLoadingSummary] = useState(true);

    // 4. Fetch the Order Summary & Agent Profile
    useEffect(() => {
        const fetchDetails = async () => {
            try {
                // A. Fetch Order Summary to get the rich Math & JSON items
                const { data: summaryData } = await client.models.BusinessData.get({ 
                    pk: businessPk, 
                    sk: `ORDER#${exactOrderId}` 
                });
                
                if (summaryData) {
                    setOrderSummary(summaryData);
                    // Extract the rich item JSON generated by crm.js
                    if (summaryData.description) {
                        try {
                            setRichItems(JSON.parse(summaryData.description));
                        } catch (e) { console.error("Could not parse rich items JSON"); }
                    }
                }

                // B. Fetch Agent Profile (if missing)
                if (!agentProfileName && agentId && agentId !== "Unassigned" && phoneNbr) {
                    const { data: agentData } = await client.models.BusinessData.get(
                        { pk: businessPk, sk: agentId },
                        { authMode: 'apiKey' }
                    );
                    if (agentData && agentData.name) {
                        setAgentProfileName(agentData.name);
                    }
                }
            } catch (err) {
                console.error("Failed to fetch advanced order details:", err);
            } finally {
                setLoadingSummary(false);
            }
        };

        fetchDetails();
    }, [agentId, businessPk, exactOrderId, phoneNbr, agentProfileName]);

    const statusColors = {
        ORDERED: 'bg-blue-500',
        IN_PREPARATION: 'bg-yellow-500',
        PREPARED: 'bg-green-500',
        DELIVERED: 'bg-gray-500',
        DELIVERING: 'bg-orange-500'
    };

    const badgeColor = statusColors[orderStatus] || 'bg-slate-600';
    const displayPhone = safeExtractPhone(customerId);
    const displayName = (customerName && !String(customerName).includes('undefined') && customerName !== 'unknown') 
        ? customerName 
        : "Customer";

    const displayAgentPhone = agentId ? String(agentId).replace('AGENT#', '') : 'Unassigned';
    const finalAgentDisplay = agentProfileName && agentProfileName !== 'Unknown Agent'
        ? `${agentProfileName} (${displayAgentPhone})` 
        : displayAgentPhone;

    // Use Rich Items if available, otherwise fallback to standard lineItems query
    const itemsToDisplay = richItems || lineItems;

    return (
        <div className="fixed inset-0 bg-black/70 flex items-center justify-center z-50 p-4">
            <div className="bg-slate-800 rounded-lg w-full max-w-md shadow-xl animate-fade-in-up flex flex-col max-h-[90vh]">
                
                {/* HEADER */}
                <div className="p-4 border-b border-slate-700 flex justify-between items-start shrink-0">
                    <div className="flex flex-col gap-1">
                        <h2 className="text-sm font-bold text-orange-400 bg-black/10 px-2 py-0.5 rounded inline-block w-fit">
                            {exactOrderId.split('#')[0]}
                        </h2>
                        
                        <div className="mt-2">
                            <h2 className="text-base font-bold text-white flex items-center gap-2">
                                {displayName}
                                {orderSummary?.activeOfferType && orderSummary.activeOfferType !== "NONE" && (
    <span className="text-[9px] bg-fuchsia-600 text-white px-2 py-0.5 rounded-full uppercase tracking-wider">
        VIP Member
    </span>
)}
                            </h2>
                            <h2 className="text-xs font-medium text-slate-400 font-mono tracking-wide">{displayPhone}</h2>
                        </div>
                    </div>
                    
                    <div className="flex flex-col items-end gap-2">
                        <button onClick={onClose} className="text-slate-400 hover:text-white text-2xl leading-none mb-1">&times;</button>
                        
                        <span className={`px-2 py-1 text-[10px] rounded-md text-white font-bold uppercase tracking-wide shadow-sm ${badgeColor}`}>
                            {orderStatus ? orderStatus.replace('_', ' ') : 'N/A'}
                        </span>

                        {(orderStatus === 'DELIVERED' || orderStatus === 'DELIVERING') && agentId && (
                            <span className="text-[10px] font-mono text-slate-400 mt-1 bg-slate-900/50 px-2 py-1 rounded border border-slate-700 flex items-center gap-1">
                                🚚 <span className="text-emerald-400 font-bold">{finalAgentDisplay}</span>
                            </span>
                        )}
                    </div>
                </div>

                {/* BODY (Scrollable Items) */}
                <div className="p-4 overflow-y-auto flex-1">
                    <div className="flex justify-between font-bold text-xs uppercase tracking-wider mb-3 text-slate-500 border-b border-slate-700 pb-2">
                        <h3 className="text-sky-400">Items</h3>
                        <h3 className="text-amber-400">Amount (BD)</h3>
                    </div>

                    <ul className="space-y-3 text-slate-300">
                        {itemsToDisplay.map((item, idx) => {
                            // Support both old database items and new Rich JSON items
                            const isRichItem = item.discountApplied !== undefined;
                            const qty = item.quantity || item.qty || 1;
                            const price = isRichItem ? (item.discountedPrice || item.unitPrice) : item.unitPrice;
                            const lineTotal = (parseFloat(price) * qty).toFixed(3);

                            return (
                                <li key={item.sk || idx} className="flex justify-between text-sm items-start">
                                    <div className="flex gap-2">
                                        <span className="font-bold text-slate-400">{qty}x</span> 
                                        <div className="flex flex-col">
                                            <span className="text-white flex items-center gap-2">
                                                {item.name}
                                                {isRichItem && item.discountApplied > 0 && (
                                                    <span className="text-[9px] bg-fuchsia-900/50 text-fuchsia-400 px-1.5 py-0.5 rounded font-bold">
                                                        -{item.discountApplied}%
                                                    </span>
                                                )}
                                            </span>
                                            {isRichItem && item.discountApplied > 0 && (
                                                <span className="text-[10px] text-slate-500 line-through">
                                                    {(item.unitPrice * qty).toFixed(3)} BD
                                                </span>
                                            )}
                                        </div>
                                    </div>
                                    <span className="font-mono text-slate-300 pt-0.5">
                                        {lineTotal}
                                    </span>
                                </li>
                            );
                        })}
                    </ul>
                    {(loading || loadingSummary) && <div className="text-center text-xs text-slate-500 py-4 animate-pulse">Loading details...</div>}
                </div>

                {/* FOOTER (Financial Breakdown) */}
                <div className="p-4 border-t border-slate-700 bg-slate-900/50 rounded-b-lg shrink-0">
                    
                    {/* 🟢 NEW: Detailed Math Breakdown */}
                    {orderSummary && (orderSummary.discountAmount > 0 || orderSummary.vatAmount > 0) && (
                        <div className="space-y-1 mb-3 text-xs text-slate-400 border-b border-slate-700 pb-3">
                            
                            {/* Subtotal (Only show if there's a discount) */}
                            {orderSummary.discountAmount > 0 && (
                                <div className="flex justify-between">
                                    <span>Original Subtotal</span>
                                    <span className="font-mono">{orderSummary.originalSubtotal?.toFixed(3)} BD</span>
                                </div>
                            )}

                            {/* VIP Discount */}
                            {orderSummary.discountAmount > 0 && (
                                <div className="flex justify-between text-fuchsia-400 font-bold">
                                    <span>VIP Discount {orderSummary.activeOfferValue ? `(${orderSummary.activeOfferValue}%)` : ''}</span>
                                    <span className="font-mono">-{orderSummary.discountAmount?.toFixed(3)} BD</span>
                                </div>
                            )}

                            {/* VAT */}
                            {orderSummary.vatAmount > 0 && (
                                <div className="flex justify-between">
                                    <span>VAT {orderSummary.vatRate ? `(${orderSummary.vatRate}%)` : ''}</span>
                                    <span className="font-mono">+{orderSummary.vatAmount?.toFixed(3)} BD</span>
                                </div>
                            )}
                        </div>
                    )}

                    {/* Final Total */}
                    <div className="flex justify-between items-center font-black text-orange-400 bg-orange-900/10 p-3 rounded-lg">
                        <span className="uppercase text-xs tracking-wider">Total Paid</span>
                        <span className="text-lg font-mono">BD {orderTotal ? parseFloat(orderTotal).toFixed(3) : '0.000'}</span>
                    </div>
                </div>

            </div>
        </div>
    );
};

export default OrderDetailModal;