// src/main.tsx
import React from 'react';
import ReactDOM from 'react-dom/client';
import { Amplify } from 'aws-amplify';
import { Authenticator, AuthenticatorProps } from '@aws-amplify/ui-react';
import '@aws-amplify/ui-react/styles.css';
import outputs from '../amplify_outputs.json';   // <-- generated by `amplify pull`
import App from './App.tsx';

// ---- 1. CONFIGURE AMPLIFY BEFORE ANYTHING ELSE ----
Amplify.configure(outputs);
// -------------------------------------------------

const formFields: AuthenticatorProps['formFields'] = {
  signUp: {
    phone_number: {
      order: 3,
      label: 'Phone Number',
      placeholder: '+15551234567',
      isRequired: true,
    },
    email: { order: 1 },
    password: { order: 2 },
    confirm_password: { order: 4 },
  },
};

ReactDOM.createRoot(document.getElementById('root')!).render(
  <React.StrictMode>
    <Authenticator formFields={formFields}>
      {({ signOut, user }) => (
        <App signOut={() => signOut?.()} user={user} />
      )}
    </Authenticator>
  </React.StrictMode>
);